ehrms/urls.py
from django.urls import include, re_path
from ehrms import Employviews,adminviews

app_name = 'ehrms'
urlpatterns = [

    re_path(r'^calendar/$', Employviews.CalendarView.as_view(), name='calendar'),
    re_path(r'^secondcalendar/$', Employviews.SecondCalendarView.as_view(), name='secondcalendar'),
    re_path('employ_apply_leave/', Employviews.employ_apply_leave, name='employ_apply_leave'),
    re_path(r'^calendar1/$', adminviews.CalendarView_1.as_view(), name='calendar1'),
    re_path(r'^calendar2/$', adminviews.CalendarView_2.as_view(), name='calendar2'),
    # re_path(r'^calendar2/$', Employviews.CalendarView1.as_view(), name='calendar2'),


]

worktride/urls.py
# """
# URL configuration for Developtreeshrms project.

# The `urlpatterns` list routes URLs to views. For more information please see:
#     https://docs.djangoproject.com/en/4.2/topics/http/urls/
# Examples:
# Function views
#     1. Add an import:  from my_app import views
#     2. Add a URL to urlpatterns:  path('', views.home, name='home')
# Class-based views
#     1. Add an import:  from other_app.views import Home
#     2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
# Including another URLconf
#     1. Import the include() function: from django.urls import include, path
#     2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
# """
from django.contrib import admin
from django.urls import path,re_path
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import TemplateView
from ehrms import views,Employviews,adminviews
from ehrms import views
from worktride import settings
from django.conf import settings
import notifications.urls


urlpatterns = [
    path("admin/", admin.site.urls),
    re_path('^inbox/notifications/', include(notifications.urls, namespace='notifications')),
    path('nav',views.nav),
    path('demo',views.showDemoPage),
    path('show_login/',views.ShowLoginPage,name="show_login"),
    path('signup_admin',views.signup_admin,name="signup_admin"),
    path('do_admin_signup',views.do_admin_signup,name="do_admin_signup"),
    path('signup_employ',views.signup_employ,name="signup_employ"),
    path('do_employ_signup',views.do_employ_signup,name="do_employ_signup"),
    path('get_user_details', views.GetUserDetails),
    path('logout_user', views.logout_user,name="logout"),
    path('doLogin',views.doLogin,name="do_login"),
    path('ehrms/',include('django.contrib.auth.urls')),
    path('admin_home',adminviews.admin_home,name="admin_home"),
    path('productivity5_create/',views.productivity5_create,name='productivity5_create'),
    path('productivity5_list/',views.productivity5_list,name='productivity5_list'),
    path('productivity5_update/<int:pk>/update/', views.productivity5_update, name='productivity5_update'),
    path('productivity5_delete/<int:pk>/delete/', views.productivity5_delete, name='productivity5_delete'),

    path('navbar/', views.navbar, name='navbar'),
    path('navbaritems/', views.navbaritems, name='navbaritems'),
    path('navbaritems_insert/', views.navbaritems_insert, name='navbaritems_insert'),
    path('navbaritems_edit/<int:id>', views.navbaritems_edit, name='navbaritems_edit'),
    path('navbaritems_update/<int:id>', views.navbaritems_update, name='navbaritems_update'),
    path('navbaritems_delete/<int:id>', views.navbaritems_delete, name='navbaritems_delete'),

    path('footer_table/',views.footer_table,name="footer_table"),

    path('footer_service/',views.footer_service,name="footer_service"),
    path('footer_service_edit/<int:id>', views.footer_service_edit, name='footer_service_edit'),
    path('footer_service_update/<int:id>', views.footer_service_update, name='footer_service_update'),
    path('footer_service_delete/<int:id>', views.footer_service_delete, name='footer_service_delete'),

    path('footer_social/',views.footer_social,name="footer_social"),
    path('footer_social_edit/<int:id>', views.footer_social_edit, name='footer_social_edit'),
    path('footer_social_update/<int:id>', views.footer_social_update, name='footer_social_update'),
    path('footer_social_delete/<int:id>', views.footer_social_delete, name='footer_social_delete'),

    path('footer_contact/',views.footer_contact,name="footer_contact"),
    path('footer_contact_edit/<int:id>', views.footer_contact_edit, name='footer_contact_edit'),
    path('footer_contact_update/<int:id>', views.footer_contact_update, name='footer_contact_update'),
    path('footer_contact_delete/<int:id>', views.footer_contact_delete, name='footer_contact_delete'),

    path('footer_link/',views.footer_link,name="footer_link"),
    path('footer_link_edit/<int:id>', views.footer_link_edit, name='footer_link_edit'),
    path('footer_link_update/<int:id>', views.footer_link_update, name='footer_link_update'),
    path('footer_link_delete/<int:id>', views.footer_link_delete, name='footer_link_delete'),



    path('start_capture/', Employviews.ScreenshotView.start_capture, name='start_capture'),
    path('stop_capture/', Employviews.ScreenshotView.stop_capture, name='stop_capture'),
    path('powercheck/', Employviews.powercheck , name="powercheck"),
    path('update-status/<str:status_type>/<str:status_message>/',Employviews.update_status, name='update_status'),
    path('update_default_sal_structure/',adminviews.update_default_sal_structure,name="update_default_sal_structure"),
    path('delete_default_sal_structure/<int:id>/', adminviews.delete_default_sal_structure, name='delete_default_sal_structure'),



    path('start_tracking/', Employviews.start_activity_tracking, name='start_tracking'),
    path('stop_and_save/', Employviews.stop_and_save_activities, name='stop_and_save'),
    path('view-app-web/<int:employee_id>/', adminviews.view_app_web,name="view_app_web" ),
    path('depth-view-app-web/<int:employee_id>/', adminviews.depth_view_app_web, name="depth_view_app_web"),
    path('ss-monitoring/<int:employee_id>/', adminviews.ss_monitoring, name="ss_monitoring"),
    path('power-monitoring/<int:employee_id>/', adminviews.power_monitoring , name="power_monitoring"),

    path('moni-dashboard/<int:employee_id>/',adminviews.moni_dashboard , name="moni_dashboard"),
    path('testingcards/',adminviews.testingcards , name="testingcards"),
    path('create_wp/',adminviews.create_wp , name="create_wp"),
    path('delete_default_sal_str/<int:salarystruct_id>/', adminviews.delete_default_sal_str, name='delete_default_sal_str'),
    path('employee_time/<int:employee_id>/',adminviews.employee_records, name="employee_records"),
    path('emp_time/',adminviews.employ_time,name='employ_time'),


    path('company_list/',views.company_list,name="company_list"),
    
    path('check_empid/',adminviews.check_empid,name="check_empid"),


    # path('add_employ', adminviews.add_employ,name="add_employ"),
    path('add_employee', adminviews.add_employee,name="add_employee"),
    path('add_admin', adminviews.add_admin,name="add_admin"),
    path('add_admin_save', adminviews.add_admin_save,name="add_admin_save"),
    # path('check_email_exist', adminviews.check_email_exist,name="check_email_exist"),
    path('check_empid_exist', adminviews.check_empid_exist,name="check_empid_exist"),
    path('check_contactno_exist', adminviews.check_contactno_exist,name="check_contactno_exist"),
    path('nav1_insertform/',views.nav1_insertform,name="nav1_insertform"),
    path('nav_retrieve/',views.nav_retrieve,name="nav_retrieve"),
    path('nav2_insertform/',views.nav2_insertform,name="nav2_insertform"),
    path('nav2_retrieve/',views.nav2_retrieve,name="nav2_retrieve"),

    path('footerinst',views.footerinst),
    path('footerretrive',views.footerretrive),
    path('store_phone_number/', views.store_phone_number, name='store_phone_number'),
    path('send_otp/', views.send_otp, name='send_otp'),
    path('verify_otp/', views.verify_otp, name='verify_otp'),
    path('register_company/<int:id>/', views.register_company, name='register_company'),
   
    path('check_username_existadmin/',views.check_username_existadmin,name="check_username_existadmin"),
    path('check_email_existadmin/',views.check_email_existadmin,name="check_email_existadmin"),

   
    path('formdeatiles/<int:id>',views.formdeatiles,name="formdeatiles"),
    path('login_view/',views.login_view,name="login_view"),
    path('projectmanagement_create/',views.projectmanagement_create,name="projectmanagement_create"),
    path('projectmanagement_list/',views.projectmanagement_list,name="projectmanagement_list"),
    path('projectmanagement_update/<int:pk>/update/', views.projectmanagement_update, name='projectmanagement_update'),
    path('projectmanagement_delete/<int:pk>/delete/', views.projectmanagement_delete, name='projectmanagement_delete'),

    path('projectmanagement2_create/',views.projectmanagement2_create,name="projectmanagement2_create"),
    path('projectmanagement2_list/',views.projectmanagement2_list,name='projectmanagement2_list'),
    path('projectmanagement2_update/<int:pk>/update/', views.projectmanagement2_update, name='projectmanagement2_update'),
    path('projectmanagement2_delete/<int:pk>/delete/', views.projectmanagement2_delete, name='projectmanagement2_delete'),


    path('projectmanagement3_create/',views.projectmanagement3_create,name='projectmanagement3_create'),
    path('projectmanagement3_list/',views.projectmanagement3_list,name='projectmanagement3_list'),
    path('projectmanagement3_update/<int:pk>/update/', views.projectmanagement3_update, name='projectmanagement3_update'),
    path('projectmanagement3_delete/<int:pk>/delete/', views.projectmanagement3_delete, name='projectmanagement3_delete'),
    path('all_projects/', views.all_projects, name='all_projects'),

    path('employeemonitoring1/', views.employeemonitoring1, name='employeemonitoring1'),
    path('employeemonitoring2/', views.employeemonitoring2, name='employeemonitoring2'),
    path('employeemonitoring3/', views.employeemonitoring3, name='employeemonitoring3'),
    path('edit_employee/<int:pk>/',views.edit_employee_index, name='edit_employeeindex_data'),
    path('delete_employee/<int:pk>/',views.delete_employee_index, name='delete_employeeindex_data'),
    path('display_employeeindex_data/',views.display_employeeindex_data, name='display_employeeindex_data'),
    
    path('edit_employeeindex1/<int:pk>/',views.edit_employeeindex1, name='edit_employeeindex1'),
    path('delete_employeeindex1/<int:pk>/',views.delete_employeeindex1, name='delete_employeeindex1'),

ehrms/forms.py
# from tkinter.tix import Form
from django import forms
from django.forms import ChoiceField

from ehrms.models import  Employs,Employee,ContactInfo2

class ChoiceNoValidation(ChoiceField):
    def validate(self, value):
        pass

class DateInput(forms.DateInput):
    input_type = "date"

class AddEmployForm(forms.Form):
    email=forms.EmailField(label="Email",max_length=50,widget=forms.EmailInput(attrs={"class":"form-control","autocomplete":"off"}))
    password=forms.CharField(label="Password",max_length=50,widget=forms.PasswordInput(attrs={"class":"form-control"}))
    first_name=forms.CharField(label="First Name",max_length=50,widget=forms.TextInput(attrs={"class":"form-control"}))
    last_name=forms.CharField(label="Last Name",max_length=50,widget=forms.TextInput(attrs={"class":"form-control"}))
    Manager=forms.CharField(label="Manager",max_length=50,widget=forms.TextInput(attrs={"class":"form-control"}))
    username=forms.CharField(label="Username",max_length=50,widget=forms.TextInput(attrs={"class":"form-control","autocomplete":"off"}))
    empid=forms.CharField(label="empid",max_length=50,widget=forms.TextInput(attrs={"class":"form-control","autocomplete":"off"}))
    role=forms.CharField(label="role",max_length=50,widget=forms.TextInput(attrs={"class":"form-control"}))
    location=forms.CharField(label="location",max_length=50,widget=forms.TextInput(attrs={"class":"form-control"}))
    package=forms.IntegerField(label="package",widget=forms.NumberInput(attrs={"class":"form-control"}))
    address=forms.CharField(label="Address",max_length=50,widget=forms.TextInput(attrs={"class":"form-control"}))
    pincode=forms.IntegerField(label="pincode",widget=forms.NumberInput(attrs={"class":"form-control"}))

    gender_choice=(
        ("Male","Male"),
        ("Female","Female")
    )

    sex=forms.ChoiceField(label="Sex",choices=gender_choice,widget=forms.Select(attrs={"class":"form-control"}))
    profile_pic=forms.FileField(label="Profile Pic",max_length=50,widget=forms.FileInput(attrs={"class":"form-control"}))
    contactno=forms.IntegerField(label="contactno",widget=forms.NumberInput(attrs={"class":"form-control"}))
    dateofjoining=forms.DateField(label="dateofjoining",widget=forms.DateInput(attrs={"class":"form-control"}))

class EditEmployForm(forms.Form):
    email=forms.EmailField(label="Email",max_length=50,widget=forms.EmailInput(attrs={"class":"form-control"}))
    first_name=forms.CharField(label="First Name",max_length=50,widget=forms.TextInput(attrs={"class":"form-control"}))
    last_name=forms.CharField(label="Last Name",max_length=50,widget=forms.TextInput(attrs={"class":"form-control"}))
    Manager=forms.CharField(label="Manager",max_length=50,widget=forms.TextInput(attrs={"class":"form-control"}))
    username=forms.CharField(label="Username",max_length=50,widget=forms.TextInput(attrs={"class":"form-control"}))
    empid=forms.CharField(label="empid",max_length=50,widget=forms.TextInput(attrs={"class":"form-control"}))
    role=forms.CharField(label="role",max_length=50,widget=forms.TextInput(attrs={"class":"form-control"}))
    location=forms.CharField(label="location",max_length=50,widget=forms.TextInput(attrs={"class":"form-control"}))
    package=forms.IntegerField(label="package",widget=forms.NumberInput(attrs={"class":"form-control"}))
    address=forms.CharField(label="Address",max_length=50,widget=forms.TextInput(attrs={"class":"form-control"}))
    pincode=forms.IntegerField(label="pincode",widget=forms.NumberInput(attrs={"class":"form-control"}))

   

    gender_choice=(
        ("Male","Male"),
        ("Female","Female")
    )

    sex=forms.ChoiceField(label="Sex",choices=gender_choice,widget=forms.Select(attrs={"class":"form-control"}))
    profile_pic=forms.FileField(label="Profile Pic",max_length=50,widget=forms.FileInput(attrs={"class":"form-control"}),required=False)
    contactno=forms.IntegerField(label="contactno",widget=forms.NumberInput(attrs={"class":"form-control"}))
    dateofjoining=forms.DateField(label="dateofjoining",widget=forms.DateInput(attrs={"class":"form-control"}))

class dataForm(forms.ModelForm):
    class Meta:
        model = Employee
        fields = '__all__'



from .models import YourModel

class YourForm(forms.ModelForm):
    class Meta:
        model = YourModel
        fields = ('all',)





from .models import Screenshots

class ScreenshotsForm(forms.ModelForm):
    class Meta:
        model = Screenshots
        fields = ['image']



class ContactInfo2Form(forms.ModelForm):
    class Meta:
        model = ContactInfo2
        fields = [
            'address',
            'city',
            'state',
            'zip_code',
            'country',
            'phone_number',
            'phone_hours',
            'email_addresses',
        ]
        widgets = {
            'email_addresses': forms.Textarea(attrs={'rows': 3}),  # Adjust textarea for email entry
        }

    def clean_email_addresses(self):
        email_addresses = self.cleaned_data['email_addresses']
        # Validate email addresses here (e.g., using a regular expression)
        return email_addresses


from .models import IntroContent, Step,Trail,clock,assignqns3,breaksqns4

class IntroContentForm(forms.ModelForm):
    class Meta:
        model = IntroContent
        fields = ['title', 'intro_text', 'setup_text', 'image','image2']

class StepForm(forms.ModelForm):
    class Meta:
        model = Step
        fields = ['intro_content', 'step_text']




class TrailForm(forms.ModelForm):
    class Meta:
        model = Trail
        fields = ['title', 'steps', 'image']


class InstructionForm(forms.ModelForm):
    class Meta:
        model = clock  # Specify the model to use
        fields = ['title', 'des1', 'des2', 'steps']  # Specify which fields to include in the form

class InstructionForm1(forms.ModelForm):
    class Meta:
        model = assignqns3  
        fields = ['title', 'des1', 'des2', 'steps']  



class InstructionForm2(forms.ModelForm):
    class Meta:
        model = breaksqns4  
        fields = ['title', 'des1', 'des2', 'steps']  

ehrms/templates/admin-template/defaultform_salary_str.html
{% extends "admin-template/base_template.html" %}
{% block main_content %}
<html>
    <head>
        <title></title>
      <style>
  b {
text-transform: capitalize;
}
</style>
    </head>
    <body>
        <div class="row justify-content-center">
  <div class="col-lg-8 col-12">
      <h4>WE😍DEVELOPTREES</h4><br><br>

    
       <form method="post" enctype="multipart/form-data">{% csrf_token %}
          <label style="color:white;">Default Salary Structure</label><br>
  <div class="form-control" style="background-color:#282f51; color:white; width:auto;height:auto; text-align:center; border:none;">
    <label>
      1. You can customize the default salary structure that xpayroll uses for your employee<br>
      2. Employer contributions to PF and ESI (if applicable) are applied after the salary has been bifurcated into the components at the ratio defined. Hence, the final salary structure can have a slightly different ratio.
    </label>
  </div>
  <br>       
        
        
        
        <div class="form-check">
            <label class="form-check-label" style="color:white;">
                <input type="checkbox" name="default_salary" class="form-check-input" value="yes" {% if post.default_salary %} checked {% endif %}>
                Use Xpayroll's Default Salary Structure (recommended)
            </label><br><br><r></r>
    
        </div>
            <div class="form-group">
                <label>salarycomponent</label>
                <input type="text" name="salarycomponent" class="form-control"  style="background-color:#282f51; border:none;color:white;"><br>
            </div>
            <div class="form-group">
                <label>percentageofCTC</label>
                <input type="text" name="percentageofCTC" class="form-control" style="background-color:#282f51; border:none;color:white;"><br>
            </div>
            <div class="form-group">
                <label>percentageorfixed</label>
                <input type="text" name="percentageorfixed" class="form-control" style="background-color:#282f51; border:none;color:white;"><br>
            </div>
            <div class="form-group">
                <label>Taxable</label>
                <input type="text" name="Taxable" class="form-control"  style="background-color:#282f51; border:none;color:white;"><br>
            </div>
             <h6>*indicates required fields</h6>
            <br>
            <input type="submit" class="btn btn-success btn-lg">
        </form></center>
    </body>            
</html>


    {% endblock main_content %}

ehrms/templates/admin-template/employ_calendar.html
{% extends 'admin-template/base_template.html' %}

{% block main_content %}
<title>Leaves And Attendance</title>
<style>
    .calendar {
  width: 99%;
  margin: auto;
  font-size: 13px;
  background-color: black;

}

.calendar tr{
  border: 1px solid black;
}

.calendar th {
  padding: 10px;
  text-align: center;
  font-size: 18px;
  color:azure;
  /* background-color: rgb(56, 56, 63); */
}

.calendar td {
  width: 50px;
  height: 50px;
  padding: 20px 0px 0px 5px;
  color:black;
  text-align: center;
  background: linear-gradient(rgb(239,239,247),rgb(238,242,244));
  font-size: 18px;
  
}
.calendar td:hover{
  color:rgb(255, 2, 2);
  
}
.calendar td::select{
  background-color: gray;
}

.month {
  font-size: 25px;
}

.date {
  font-size: 16px;
}
/* .calendar
ul {
  height: 100px;
  text-align: center;
} */

a {
  color: #17a2b8;
}
.left {
  float: left;
}
.center {
  float: center;
}

.right {
  float: right;
}

.btn {
  outline: none;
  color:white;
  background-color: transparent;
  box-shadow: 0 0 0 0;
}

.clearfix {
  margin-top: 20px;
  text-align: center;
  background-color: rgb(41,215,231);
  flex-grow: 1;
  height: 40px;
  border: none;
  color: black;
  
}
.check{
  background-color: rgb(239,239,247);
  padding:25px;
  display:row;
  flex-direction: row;
  justify-content: center;
}
td.datepresent{
  color: rgb(0, 0, 0);
  background-color: rgba(246, 230, 0, 0.311);
}
td.datepresent1{
  color: green;
  background-color: rgba(229, 255, 0, 0.451);
}
span.datepresent1{
  color: rgb(95, 255, 3);
  
}
/* .area{
	padding: 10px;
	height: auto;
} */
.check_notify{
  background-color: green;
  color:white;
}
/* .button{
  background-color: rgb(26, 31, 182);
  color:white;
} */
button:disabled {
  cursor: not-allowed;
  pointer-events: all !important;
}

/* @media screen and (max-width: 768px){
  div{
        font-size: 18px;
        display: flex;
  }
  
} */

  </style>
  <br>
  <br>

{% if messages %}
<ul class="messages">
    {% for message in messages %}
        <li{% if message.tags %} class="{{ message.tags }}"{% endif %} style="background-color: green;color: whitesmoke;padding: 10px;list-style-type: none;width: 70%;">{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}

    <div class="col-md-2"></div>
    <div class="col-md-12">
      <h1 style="color:black;">Leave & Attendances</h1>
      
      <div  class="check">
        <div class="row justify-content-between">
        <div sytle="flex-direction:column;">
        <h2 style="color:black; font-size:24px;">Mark attendance for today(<span id="date"></span>)</h2>
        <!-- <p style="color:white; font-size:16px;">You can mark your attendance for today. For any other day, please use the edit option below.</p> -->
      </div>
      
        {% comment %} <div class="col">
          
          <form method="post" id="checkInForm" enctype="multipart/form-data">
            {% csrf_token %}
            <button class="btn btn-info" name="v" id="checkInBtn" type="submit" style="color: white;border: none; background-color: #4358c2;" style="width:300px">Check In</button>
          </form><br>

          
          
  
          <form method="post" id="checkOutForm" enctype="multipart/form-data">
            {% csrf_token %}
            <button class="btn btn-info" name="v1" type="submit" style="color: white; border: none; background-color: #4358c2" >Check Out</button>
          </form>
        </div>
      </div>
    </div>      {% endcomment %}
        <script>
        n =  new Date();
        y = n.getFullYear();
        m = n.getMonth() + 1;
        d = n.getDate();
        document.getElementById("date").innerHTML = d + "/" + m + "/" + y;
        </script>
 
        
<div class="clearfix">
	<a class="btn btn-info left" href="{% url 'ehrms:calendar2' %}?{{ prev_month }}" style="margin-left: 8px;"><span></span>Prev</a>
	<a class="btn btn-info center" href="{% url 'ehrms:calendar2' %}?{{ get_date }}"> Today </a>
	<a class="btn btn-info right" href="{% url 'ehrms:calendar2' %}?{{ next_month }}" style="margin-right: 10px;"> Next>> </a>
</div>
</div>
<br>
<div class="table-responsive">
<div class="TFtable">
  {{ calendar }}
</div>
</div>

<script>
  document.addEventListener("DOMContentLoaded", function() {
      
      setTimeout(function() {
          const messages = document.querySelectorAll('.messages li');
          messages.forEach(function(message) {
              message.style.opacity = '0';
              setTimeout(function() { 
                  message.style.display = 'none';
              }, 600);
          });
      }, 5000); 
  });
  </script>



{% endblock main_content %}

ehrms/templates/admin-template/interview_settings.html
<!DOCTYPE html>
<html>
<head>
    <title>Interview Settings Form</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <style>
        .container {
    max-width: 600px;
    margin: 50px auto;
    padding: 30px;
    background-color: #f9f9f9;
    border-radius: 8px;
    box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
}

h2 {
    text-align: center;
    color: #333;
    margin-bottom: 20px;
}

form {
    display: flex;
    flex-direction: column;
}

label {
    font-weight: bold;
    margin-bottom: 8px;
    color: #555;
}

input[type="url"],
input[type="date"] {
    padding: 10px;
    margin-bottom: 15px;
    border: 1px solid #ccc;
    border-radius: 4px;
    font-size: 14px;
}

button.btn-primary {
    background-color: #007bff;
    color: #fff;
    border: none;
    padding: 10px 20px;
    border-radius: 4px;
    cursor: pointer;
    font-size: 16px;
}

button.btn-primary:hover {
    background-color: #0056b3;
}

@media (max-width: 768px) {
    .container {
        padding: 20px;
    }
}

@media (max-width: 576px) {
    .container {
        padding: 15px;
    }

    input[type="url"],
    input[type="date"] {
        font-size: 13px;
    }

    button.btn-primary {
        font-size: 14px;
        padding: 8px 16px;
    }
}

    </style>
</head>
<body>
    <div class="container">
        <h2>Generate Interview Link</h2>
        <form method="post">  
            {% csrf_token %}
            <input type="hidden" name="companyid" value="{{ companyid }}">

            <label for="google_meet_link">Google Meet Link:</label>
            <input type="url" id="google_meet_link" name="google_meet_link"><br><br>

            <label for="interview_time">Interview Time:</label>
            <input type="date" id="interview_time" name="interview_time"><br><br>

            <button type="submit" class="btn btn-primary">Save</button>
        </form>
    </div>
</body>
</html>

ehrms/templates/admin-template/runpayroll.html
<html>
    <head>
        <title></title>
        <style>
             form{
                background-color:#1E2442;
                color: white;
                margin-top: 40px;
                text-align: center;
                font-size:xx-large;
            }
            body{
                background-color: #1E2442;
            }
        </style>
    </head>
    <body>
       <center> <form method="post" enctype="multipart/form-data" action="/runpay_update/{{post.id}}" style="border: 2px solid black; width: 30%; height: 280px;">{% csrf_token %}
            
            <div class="form-group">
                <label>name</label>
                <input type="text" name="name" class="form-control" value="{{post.name}}"><br>
            </div>
            <div class="form-group">
                <label>monthly_ctc</label>
                <input type="number" name="monthly_ctc" class="form-control" value="{{post.monthly_ctc}}"><br>
            </div>
            <div class="form-group">
                <label>addition</label>
                <input type="number" name="addition" class="form-control" value="{{post.addition}}"><br>
            </div>
            <div class="form-group">
                <label>deduction</label>
                <input type="number" name="deduction" class="form-control" value="{{post.deduction}}"><br>
            </div>
            <div class="form-group">
                <label>reimbursement</label>
                <input type="number" name="reimbursement" class="form-control" value="{{post.reimbursement}}"><br>
            </div>
            <div class="form-group">
                <label>remarks</label>
                <input type="text" name="remarks" class="form-control" value="{{post.remarks}}"><br>
            </div>
            <div class="form-group">
                <label>gross_pay</label>
                <input type="number" name="gross_pay" class="form-control" value="{{post.gross_pay}}"><br>
            </div>
            <input type="submit" class="btn btn-success btn-lg">
        </form></center>
    </body>            
</html>